services:
  - type: web
    name: myflaskapp
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: flask run --host=0.0.0.0 --port=10000
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
